// Assi: [Intensità, Dolcezza, Classico(0)-Sperimentale(10), Sociale(0)-Intimo(10)]

const STANDARD_DRINKS = [
  { name: "Spritz", axes: [3,6,3,2], desc: "Leggero e solare, porti allegria ovunque tu vada." },
  { name: "Negroni", axes: [9,3,2,6], desc: "Deciso e senza compromessi, sai sempre cosa vuoi." },
  { name: "Americano", axes: [5,5,2,4], desc: "Equilibrato, mediti prima di scegliere." },
  { name: "Gin Tonic", axes: [6,2,4,5], desc: "Essenziale e raffinato, ti adatti senza perdere stile." },
  { name: "Mojito", axes: [4,6,3,3], desc: "Spontaneo e fresco, vivi il momento." },
  { name: "Margarita", axes: [7,4,4,4], desc: "Vivace e audace, ami sorprendere." },
  { name: "Moscow Mule", axes: [5,4,5,3], desc: "Anticonformista quel tanto che basta, originale con stile." },
  { name: "Cosmopolitan", axes: [6,6,3,5], desc: "Elegante e sicuro di sé, brilli in ogni contesto." },
  { name: "Piña Colada", axes: [3,9,3,2], desc: "Rilassato e godereccio, il relax è la tua priorità." },
  { name: "Daiquiri", axes: [6,5,3,6], desc: "Semplice ma raffinato, la sostanza prima di tutto." },
  { name: "Whiskey Sour", axes: [7,5,4,7], desc: "Equilibrio tra carattere e dolcezza, complesso quanto basta." },
  { name: "Old Fashioned", axes: [9,4,1,8], desc: "Classico e solido, i valori prima delle mode." },
  { name: "Manhattan", axes: [9,3,2,8], desc: "Intenso e sofisticato, non hai bisogno di alzare la voce." },
  { name: "Cuba Libre", axes: [4,7,2,2], desc: "Diretto e senza fronzoli, vai dritto al punto." },
  { name: "Bellini", axes: [2,7,3,4], desc: "Delicato e curato, ami i piccoli piaceri raffinati." },
  { name: "Hugo", axes: [2,6,4,2], desc: "Fresco e leggero, prendi la vita con filosofia." },
  { name: "Caipirinha", axes: [6,6,4,2], desc: "Vivace e diretto, energia pura in ogni gesto." },
  { name: "Tequila Sunrise", axes: [5,7,4,3], desc: "Colorato e ottimista, vedi sempre il lato positivo." },
  { name: "Bloody Mary", axes: [6,1,6,7], desc: "Deciso e imprevedibile, sorprendi chi ti conosce poco." },
  { name: "Espresso Martini", axes: [7,5,5,6], desc: "Energico e sofisticato, unisci ambizione e stile." },
  { name: "Gimlet", axes: [7,3,3,7], desc: "Preciso e riservato, la qualità conta più della quantità." },
  { name: "French 75", axes: [6,4,4,6], desc: "Elegante e frizzante, sai farti notare senza sforzo." },
  { name: "Amaretto Sour", axes: [5,8,4,5], desc: "Dolce ma con carattere, morbido fuori, deciso dentro." },
  { name: "Sex on the Beach", axes: [3,8,3,2], desc: "Solare e disinvolto, ami la leggerezza della compagnia." },
  { name: "Long Island Iced Tea", axes: [9,5,5,2], desc: "Intenso e complesso, non ti accontenti del semplice." },
  { name: "Mai Tai", axes: [6,7,5,3], desc: "Esotico e curioso, cerchi sempre nuove esperienze." },
  { name: "Dark 'n' Stormy", axes: [6,5,4,5], desc: "Deciso ma equilibrato, sai gestire ogni tempesta." },
  { name: "Campari Spritz", axes: [5,4,3,3], desc: "Amaro e diretto, non hai paura di distinguerti." },
  { name: "Sidecar", axes: [7,4,3,7], desc: "Raffinato e deciso, un classico che non passa mai di moda." },
  { name: "Kentucky Mule", axes: [7,4,5,5], desc: "Robusto e originale, tradizione con un twist personale." },
];

const SPECIAL_DRINKS = [
  { name: "Last Word", axes: [8,3,8,8], desc: "Complesso ed equilibrato, ogni parte di te ha un ruolo preciso." },
  { name: "Sazerac", axes: [9,3,6,9], desc: "Rituale e intenso, ami fare le cose con metodo." },
  { name: "Aviation", axes: [7,4,7,7], desc: "Elegante e sorprendente, nascondi profondità non ovvie." },
  { name: "Penicillin", axes: [8,4,7,7], desc: "Intenso e curativo, trasformi le difficoltà in forza." },
  { name: "Paper Plane", axes: [7,4,7,6], desc: "Bilanciato e moderno, sai stare al passo senza perdere identità." },
  { name: "Vieux Carré", axes: [9,3,6,9], desc: "Stratificato e deciso, la tua storia ha molti capitoli." },
  { name: "Corpse Reviver No. 2", axes: [7,3,8,7], desc: "Ingannevole ed elegante, più forte di quanto sembri." },
  { name: "Clover Club", axes: [5,6,7,5], desc: "Delicato mai banale, l'eleganza è nei dettagli." },
  { name: "Boulevardier", axes: [9,3,5,8], desc: "Intenso e sicuro, non temi il carattere forte." },
  { name: "Bramble", axes: [5,6,6,4], desc: "Fresco e strutturato, la semplicità apparente nasconde cura." },
  { name: "Naked and Famous", axes: [8,4,8,6], desc: "Audace ed equilibrato, ami l'estremo ma con criterio." },
  { name: "White Lady", axes: [7,3,6,7], desc: "Pulito e diretto, la chiarezza è la tua forza." },
  { name: "Jungle Bird", axes: [6,6,7,4], desc: "Esotico e strutturato, esplori senza perdere la rotta." },
  { name: "Chartreuse Swizzle", axes: [7,5,9,5], desc: "Erbaceo e sperimentale, ami ciò che pochi capiscono." },
  { name: "Bee's Knees", axes: [6,6,5,5], desc: "Dolce ma mai scontato, la semplicità fatta bene." },
  { name: "Trinidad Sour", axes: [6,4,9,6], desc: "Anticonformista e coraggioso, rompi le regole con metodo." },
  { name: "Oaxaca Old Fashioned", axes: [9,4,8,8], desc: "Affumicato e intenso, la tradizione reinventata." },
  { name: "Bobby Burns", axes: [8,3,6,8], desc: "Fiero e complesso, porti con orgoglio le tue radici." },
  { name: "Champs-Élysées", axes: [8,4,7,7], desc: "Raffinato e vivace, l'eleganza francese ti rappresenta." },
  { name: "Gold Rush", axes: [7,6,5,6], desc: "Caldo e accessibile, la ricercatezza senza pretese." },
  { name: "Suffering Bastard", axes: [7,5,6,4], desc: "Intenso e conviviale, resisti a tutto con stile." },
  { name: "Zombie", axes: [9,7,6,3], desc: "Potente e complesso, sotto la superficie nascondi molto." },
  { name: "Ramos Gin Fizz", axes: [5,6,7,6], desc: "Meticoloso e curato, la pazienza è la tua arte." },
  { name: "Blood and Sand", axes: [6,6,6,6], desc: "Equilibrato tra opposti, sai unire mondi diversi." },
  { name: "Widow's Kiss", axes: [8,6,8,8], desc: "Intenso e misterioso, poche persone ti capiscono davvero." },
  { name: "Tuxedo No. 2", axes: [7,3,7,7], desc: "Formale ma tagliente, l'eleganza con un twist amaro." },
  { name: "Hemingway Daiquiri", axes: [5,5,5,5], desc: "Bilanciato e letterario, la semplicità è la tua firma." },
  { name: "Improved Whiskey Cocktail", axes: [8,3,6,8], desc: "Classico rivisitato, migliori ciò che già funziona." },
  { name: "Kingston Negroni", axes: [9,3,8,7], desc: "Deciso e sperimentale, reinventi le regole senza tradirle." },
  { name: "Between the Sheets", axes: [8,4,6,6], desc: "Ambiguo e affascinante, ti muovi tra più mondi con disinvoltura." },
  { name: "Black Russian", axes: [8,5,5,8], desc: "Diretto e intenso, poche parole, tanta sostanza." },
  { name: "White Russian", axes: [6,7,4,8], desc: "Morbido ma presente, la dolcezza nasconde carattere." },
  { name: "Colorado Bulldog", axes: [7,6,6,7], desc: "Energico e goloso, unisci gusto e vitalità." },
  { name: "Revolver", axes: [8,5,7,8], desc: "Fumoso e magnetico — un gesto scenico (l'arancia flambé) e lasci il segno." },
  { name: "Jamaican Cocktail", axes: [7,6,7,6], desc: "Morbido ma ricercato, l'eleganza tropicale ti rappresenta." },
];

// Ogni domanda ha 3 opzioni, ognuna con un delta [Int, Dolc, C-S, S-I] da sommare al profilo (partenza 5,5,5,5)
const STANDARD_QUESTIONS = [
  { q: "Serata perfetta?", options: [
    { t: "Casa, pochi amici", d: [1,0,0,3] },
    { t: "Locale pieno di gente", d: [0,1,0,-3] },
    { t: "Qualcosa di improvvisato", d: [0,1,2,0] },
  ]},
  { q: "Al lavoro sei quello che...", options: [
    { t: "Decide in fretta", d: [3,0,0,0] },
    { t: "Media tra le parti", d: [-1,0,0,1] },
    { t: "Porta energia al team", d: [0,1,0,-2] },
  ]},
  { q: "Il tuo rapporto con le regole?", options: [
    { t: "Le rispetto se hanno senso", d: [0,0,2,0] },
    { t: "Mi danno struttura", d: [0,0,-3,1] },
    { t: "Meglio chiedere scusa dopo", d: [0,-1,3,0] },
  ]},
  { q: "Cosa non sopporti?", options: [
    { t: "L'indecisione", d: [2,0,0,0] },
    { t: "La noia", d: [0,1,2,0] },
    { t: "La superficialità", d: [0,0,-1,2] },
  ]},
  { q: "Sotto pressione come reagisci?", options: [
    { t: "Mi concentro e vado dritto", d: [3,0,0,1] },
    { t: "Mi appoggio agli altri", d: [0,0,0,-2] },
    { t: "Trovo un'alternativa", d: [0,0,2,0] },
  ]},
  { q: "Il tuo viaggio ideale?", options: [
    { t: "Città d'arte pianificata", d: [0,0,-2,1] },
    { t: "Spiaggia e relax", d: [-2,2,0,0] },
    { t: "Scoperta in gruppo", d: [0,0,1,-2] },
  ]},
  { q: "Il tuo gusto preferito?", options: [
    { t: "Amaro e deciso", d: [2,-3,0,0] },
    { t: "Dolce e fruttato", d: [0,3,0,0] },
    { t: "Fresco e agrumato", d: [0,-1,1,0] },
  ]},
  { q: "Come ti descrivono gli amici?", options: [
    { t: "Affidabile", d: [0,0,-2,1] },
    { t: "Solare", d: [0,1,0,-2] },
    { t: "Imprevedibile", d: [0,0,3,0] },
  ]},
];

const SPECIAL_QUESTIONS = [
  { q: "Il tuo bar ideale?", options: [
    { t: "Speakeasy nascosto", d: [0,0,3,2] },
    { t: "Rooftop panoramico", d: [0,1,0,-2] },
    { t: "Locale storico", d: [0,0,-2,1] },
  ]},
  { q: "Cosa cerchi davvero in un drink?", options: [
    { t: "Complessità di gusto", d: [0,0,3,0] },
    { t: "Equilibrio perfetto", d: [-1,0,1,0] },
    { t: "Un sorso che sorprende", d: [0,1,2,0] },
  ]},
  { q: "Il tuo rapporto con il tempo?", options: [
    { t: "Pazienza, il meglio arriva piano", d: [2,0,0,2] },
    { t: "Voglio risultati subito", d: [0,1,-1,0] },
    { t: "Il percorso conta più del risultato", d: [0,0,2,0] },
  ]},
  { q: "Il tuo stile?", options: [
    { t: "Elegante e misurato", d: [0,0,-1,3] },
    { t: "Audace, fuori standard", d: [1,0,3,0] },
    { t: "Versatile, mi adatto", d: [0,1,0,0] },
  ]},
  { q: "Un difetto che ti riconosci?", options: [
    { t: "Sono esigente", d: [0,0,1,2] },
    { t: "Sono impulsivo", d: [2,-1,0,0] },
    { t: "Overthinking", d: [0,0,0,3] },
  ]},
  { q: "Cosa apprezzi in una serata tra amici intimi?", options: [
    { t: "Conversazioni profonde", d: [0,0,0,3] },
    { t: "Racconti e risate", d: [0,1,0,-1] },
    { t: "Silenzi comodi", d: [1,0,0,2] },
  ]},
  { q: "Quale ingrediente ti intriga di più?", options: [
    { t: "Amari ed erbe forti", d: [2,-3,0,0] },
    { t: "Caffè e tostato", d: [1,0,0,2] },
    { t: "Affumicato / mezcal", d: [1,0,3,0] },
  ]},
  { q: "Cosa ti rappresenta di più?", options: [
    { t: "Precisione classica", d: [0,0,-3,0] },
    { t: "Sperimentazione controllata", d: [0,0,3,1] },
    { t: "Intensità pura", d: [3,0,0,0] },
  ]},
];
